name: "FHIR API endpoint for FHIR Patient Rec“

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: curl -X GET "http://hapi.fhir.org/baseR4/Patient?phonetic=tue"

